// Define and export the constant
export const OVERLAY_BACK_WITH_SELECTOR = '.nav-menu-overlay-back';
export const NAV_MENU_OVERLAY_BACK = 'nav-menu-overlay-back';
export const SUBMENU = 'submenu';
export const SUBMENU_WITH_SELECTOR = '.submenu';
export const SUBMENU_MAIN_TITLE_WITH_SELECTOR = '.submenu-main-title';
export const SUBMENU_MAIN_TITLE = 'submenu-main-title';
export const NAV_SECTIONS_WITH_SELECTOR = '.nav-sections';
export const OPEN_NAVIGATION = 'Open navigation';
export const CLOSE_NAVIGATION = 'Close navigation';
export const NAV_MENU_OVERLAY_WITH_SELECTOR = '.nav-menu-overlay';
export const OPEN = 'open';
export const KEY_DOWN = 'keydown';
export const CATEGORY = 'category';
export const FOOTER = 'footer';
export const DROPDOWN = 'dropdown';
export const LEVEL_0 = 'level0';
export const LEVEL_1 = 'level1';
export const LEVEL_2 = 'level2';
export const NAV = 'nav';
export const TRENDING_DATA_FILENAME = 'trending';

export const SEARCH_BY_COUNTRY = 'Search By Country';
export const NAV_MENU_COLUMN_RIGHT = 'nav-menu-column right';
export const NAV_MENU_COLUMN_LEFT = 'nav-menu-column left';
export const NAV_MENU = 'nav-menu';
export const NAV_MENU_OVERLAY = 'nav-menu-overlay';
export const SELECTED = 'selected';
export const COUNTRY_LIST = 'country-list';
export const COUNTRY_LIST_WITH_SELECTOR = '.country-list';

/* Language Selector Constants */
export const LANGUAGE_TOGGLE_CLASS = 'language-toggle';
export const LANGUAGE_SELECTOR_META_NAME = 'alternate-url';
export const LANGUAGE_CONTENT_CLASS = 'language-content';
export const LANGUAGE_CONTAINER_CLASS = 'language-container';
export const LANGUAGE_CONTAINER_CLASS_SELECTOR = '.language-container';
export const SHOW_SELECTED_CLASS = 'show-selected';
export const COMMA_SEPARATOR = ',';
export const PIPE_SEPARATOR = '|';
export const TYPE_CLICK = 'click';
export const LANGUAGE_CONTENT_SELECTOR = 'div.language-content';
export const LANGUAGE_TOGGLE_SELECTOR = 'div.language-toggle';
export const ATTR_ARIA_EXPANDED = 'aria-expanded';
export const CONTENT_EXPANDED = 'nav-item-content-expanded';
export const CONTENT_EXPANDED_ACTIVE = 'nav-item-expanded-active';
export const LANG_PREFIX = 'lang';
export const LANGUAGE_TOGGLE_BORDER_CLASS = 'language-toggle-border';
export const LANGUAGE_TEXT_CLASS = 'language-text';
